#https://marketplace.visualstudio.com/items?itemName=humao.rest-client
#https://learn.microsoft.com/en-us/aspnet/core/test/http-files?view=aspnetcore-8.0
#https://vscode.dev/github/Huachao/vscode-restclient

@hostname=localhost
@port=7039


#
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d 'client_id=db00e4dc-475f-495f-8349-7b93884d6fb5&scope=api://db00e4dc-475f-495f-8349-7b93884d6fb5/.default&client_secret=4ri8Q~OnIN859imaeAqF9QdNo_~o568zrFOPAb9Y&grant_type=client_credentials' 'https://login.microsoftonline.com/d2b67c64-4844-4188-a7df-429449cd1ae7/oauth2/v2.0/token'

###

# @name login
POST https://login.microsoftonline.com/d2b67c64-4844-4188-a7df-429449cd1ae7/oauth2/v2.0/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=db00e4dc-475f-495f-8349-7b93884d6fb5&scope=api://db00e4dc-475f-495f-8349-7b93884d6fb5/.default&client_secret=4ri8Q~OnIN859imaeAqF9QdNo_~o568zrFOPAb9Y&grant_type=client_credentials

###

@token = {{login.response.body.access_token}}



#get prompt template
GET https://{{hostname}}:{{port}}/api/llama/configuration/prompt-templates HTTP/1.1
Authorization: Bearer {{token}}

###
#get health status from anonymous healthcontroller
GET https://{{hostname}}:{{port}}/health HTTP/1.1

###